(() => {
  const groups = {
    pasta:{meal:'Hauptgericht',cuisine:'Westlich',image:'./images/family-recipes/pasta.webp',time:'35 Min.',ingredients:'Pasta|400 g;Zwiebel|1;Knoblauch|2 Zehen;Tomaten|400 g;Parmesan|60 g;Olivenöl|2 EL;Salz, Pfeffer und Kräuter|nach Geschmack',steps:['Pasta in reichlich Salzwasser knapp bissfest kochen.','Zwiebel und Knoblauch fein schneiden und in Olivenöl sanft anrösten. Die weiteren Hauptzutaten zugeben.','Sauce mindestens 15 Minuten leise köcheln lassen und kräftig abschmecken.','Pasta mit der Sauce verbinden, kurz ziehen lassen und mit Parmesan servieren.']},
    auflauf:{meal:'Hauptgericht',cuisine:'Westlich',image:'./images/family-recipes/auflauf.webp',time:'50 Min.',ingredients:'Kartoffeln oder Nudeln|800 g;Gemüse|500 g;Sahne|200 ml;Milch|150 ml;Käse gerieben|150 g;Zwiebel|1;Muskat, Salz und Pfeffer|nach Geschmack',steps:['Backofen auf 190 °C Ober-/Unterhitze vorheizen und die Form fetten.','Hauptzutaten vorgaren, Gemüse mundgerecht schneiden und alles in der Form verteilen.','Sahne, Milch und Gewürze verrühren, darübergießen und mit Käse bestreuen.','30–35 Minuten goldbraun backen und vor dem Servieren fünf Minuten ruhen lassen.']},
    haehnchen:{meal:'Hauptgericht',cuisine:'Westlich',image:'./images/family-recipes/haehnchen.webp',time:'40 Min.',ingredients:'Hähnchenbrust|600 g;Gemüse|600 g;Zwiebel|1;Knoblauch|2 Zehen;Olivenöl|2 EL;Brühe|200 ml;Paprikapulver, Salz und Pfeffer|nach Geschmack',steps:['Hähnchen trocken tupfen, würzen und portionsgerecht schneiden.','In einer großen Pfanne rundherum kräftig anbraten und herausnehmen.','Gemüse und Zwiebel im Bratensatz rösten, Knoblauch zugeben und mit Brühe ablöschen.','Hähnchen zurückgeben, sanft fertig garen und die Sauce abschmecken.']},
    fisch:{meal:'Hauptgericht',cuisine:'Westlich',image:'./images/family-recipes/fisch.webp',time:'30 Min.',ingredients:'Fischfilet|600 g;Kartoffeln oder Reis|800 g;grünes Gemüse|500 g;Zitrone|1;Butter oder Olivenöl|2 EL;Dill oder Petersilie|1 Bund;Salz und Pfeffer|nach Geschmack',steps:['Beilage und Gemüse vorbereiten und garen.','Fisch trocken tupfen, salzen und mit wenig Öl bei mittlerer Hitze braten oder im Ofen garen.','Zitrone, Butter und Kräuter zu einer leichten Sauce verbinden.','Fisch glasig und saftig mit Gemüse, Beilage und Kräutersauce servieren.']},
    vegetarisch:{meal:'Hauptgericht',cuisine:'International',image:'./images/family-recipes/vegetarisch.webp',time:'35 Min.',ingredients:'Gemüse gemischt|700 g;Kichererbsen oder Linsen|400 g;Zwiebel|1;Knoblauch|2 Zehen;Tomaten|400 g;Kokosmilch oder Brühe|250 ml;Reis|300 g;Gewürze|nach Geschmack',steps:['Reis oder die gewünschte Beilage garen.','Zwiebel, Knoblauch und Gewürze kurz anrösten.','Gemüse und Hülsenfrüchte zugeben, mit Tomaten und Flüssigkeit auffüllen.','15–20 Minuten cremig köcheln, frisch abschmecken und mit der Beilage servieren.']},
    suppe:{meal:'Hauptgericht',cuisine:'Westlich',image:'./images/family-recipes/suppe.webp',time:'40 Min.',ingredients:'Kartoffeln|500 g;Möhren|3;Lauch|1 Stange;Zwiebel|1;Brühe|1,2 l;Petersilie|1 Bund;Öl|1 EL;Salz und Pfeffer|nach Geschmack',steps:['Gemüse waschen, schälen und in gleichmäßige Stücke schneiden.','Zwiebel in Öl glasig dünsten, festes Gemüse kurz mitrösten.','Mit Brühe auffüllen und bei kleiner Hitze garen, bis alles weich ist.','Je nach Rezept teilweise pürieren oder stückig lassen und frisch abschmecken.']},
    kartoffeln:{meal:'Hauptgericht',cuisine:'Westlich',image:'./images/family-recipes/kartoffeln.webp',time:'40 Min.',ingredients:'Kartoffeln|1 kg;Zwiebel|1;Eier|2;Mehl|2 EL;Öl oder Butter|zum Braten;Salat oder Gemüse|500 g;Salz, Pfeffer und Muskat|nach Geschmack',steps:['Kartoffeln passend zum Gericht vorbereiten und kräftig würzen.','Zwiebel und weitere Zutaten untermischen oder separat anrösten.','In Pfanne oder Ofen langsam goldbraun und innen weich garen.','Mit frischem Salat, Gemüse oder einem leichten Dip servieren.']},
    fruehstueck:{meal:'Frühstück',cuisine:'Westlich',image:'./images/family-recipes/fruehstueck.webp',time:'20 Min.',ingredients:'Haferflocken oder Mehl|200 g;Milch|300 ml;Eier|2;Joghurt oder Quark|250 g;Obst|300 g;Honig|2 EL;Zimt|nach Geschmack',steps:['Trockene Zutaten mischen und mit Milch und Eiern zu einer glatten Grundlage verrühren.','Je nach Gericht in Pfanne oder Ofen schonend goldgelb garen.','Obst waschen und mundgerecht vorbereiten.','Mit Joghurt oder Quark, Obst und wenig Honig frisch servieren.']},
    backen:{meal:'Backen & Dessert',cuisine:'Westlich',image:'./images/family-recipes/backen.webp',time:'55 Min.',ingredients:'Mehl|300 g;Butter|150 g;Zucker|100 g;Eier|3;Milch|150 ml;Obst oder Schokolade|300 g;Backpulver|1 Päckchen;Vanille und Zimt|nach Geschmack',steps:['Backofen vorheizen und Form fetten oder mit Backpapier auslegen.','Butter, Zucker und Eier cremig rühren, dann Mehl, Backpulver und Milch kurz einarbeiten.','Früchte oder Schokolade unterheben und den Teig gleichmäßig verteilen.','Goldbraun backen, Stäbchenprobe machen und vor dem Schneiden auskühlen lassen.']},
    orientalisch:{meal:'Hauptgericht',cuisine:'Persisch',image:'./images/family-recipes/orientalisch.webp',time:'55 Min.',ingredients:'Basmatireis|350 g;Hähnchen oder Hülsenfrüchte|600 g;Zwiebeln|2;Safran oder Kurkuma|1 TL;Kräuter|1 Bund;Joghurt|250 g;Zitrone|1;Salz und Pfeffer|nach Geschmack',steps:['Reis gründlich waschen, in Salzwasser vorkochen und abgießen.','Zwiebeln goldbraun rösten, Hauptzutaten und Gewürze zugeben und sanft garen.','Reis im Topf locker dämpfen, damit er körnig bleibt und eine goldene Kruste entstehen kann.','Mit frischen Kräutern, Zitronensaft und Joghurt gemeinsam anrichten.']}
  };
  const dishes = {
    pasta:[['Spaghetti Bolognese','Spaghetti|400 g;Rinderhack|500 g;Möhren|2;Staudensellerie|2 Stangen'],['Lasagne klassisch','Lasagneplatten|12;Rinderhack|500 g;Béchamelsauce|500 ml'],['Spaghetti Carbonara familienfreundlich','Spaghetti|400 g;Speck|150 g;Eier|3;Parmesan|100 g'],['Tomaten-Mozzarella-Pasta','Penne|400 g;Mozzarella|250 g;Kirschtomaten|500 g;Basilikum|1 Bund'],['Cremige Hähnchen-Pasta','Penne|400 g;Hähnchenbrust|500 g;Champignons|300 g;Sahne|200 ml'],['Lachs-Spinat-Nudeln','Tagliatelle|400 g;Lachsfilet|500 g;Blattspinat|400 g;Frischkäse|150 g'],['One-Pot-Tomatenpasta','Linguine|400 g;Kirschtomaten|500 g;Gemüsebrühe|800 ml;Frischkäse|100 g'],['Tortellini in Schinken-Sahne-Sauce','Tortellini|750 g;Kochschinken|200 g;Erbsen|200 g'],['Cremige Mac and Cheese','Makkaroni|400 g;Cheddar|250 g;Milch|500 ml'],['Nudelauflauf mit Gemüse','Penne|400 g;Zucchini|2;Paprika|2']],
    auflauf:[['Kartoffel-Brokkoli-Auflauf','Kartoffeln|1 kg;Brokkoli|600 g'],['Blumenkohl-Hack-Auflauf','Blumenkohl|1 Kopf;Rinderhack|500 g'],['Gnocchi-Tomaten-Auflauf','Gnocchi|800 g;Kirschtomaten|500 g;Mozzarella|250 g'],['Tortellini-Auflauf','Tortellini|750 g;Spinat|300 g;Frischkäse|150 g'],['Zucchini-Reis-Auflauf','Zucchini|3;Reis|300 g;Feta|200 g'],['Hähnchen-Nudel-Auflauf','Hähnchenbrust|500 g;Penne|350 g;Erbsen|200 g'],['Lachs-Kartoffel-Gratin','Lachs|500 g;Kartoffeln|1 kg;Dill|1 Bund'],['Gemüse-Lasagne','Lasagneplatten|12;Zucchini|2;Aubergine|1'],['Moussaka mild','Kartoffeln|700 g;Auberginen|2;Rinderhack|500 g'],['Schupfnudel-Gemüse-Pfanne überbacken','Schupfnudeln|800 g;Paprika|2;Zucchini|2']],
    haehnchen:[['Honig-Senf-Hähnchen','Honig|2 EL;Senf|2 EL;Kartoffeln|800 g'],['Ofenhähnchen mit Wurzelgemüse','Kartoffeln|600 g;Möhren|4;Pastinaken|2'],['Hähnchen-Geschnetzeltes','Champignons|300 g;Sahne|200 ml;Spätzle|500 g'],['Paprika-Hähnchen-Pfanne','Paprika|3;Reis|300 g;Tomatenmark|2 EL'],['Mildes Hähnchen-Curry','Kokosmilch|400 ml;Möhren|3;Erbsen|200 g'],['Hähnchen-Fajitas','Tortillas|8;Paprika|3;Mais|1 Dose'],['Knusprige Hähnchenschnitzel','Paniermehl|150 g;Eier|2;Kartoffeln|800 g'],['Teriyaki-Hähnchen mit Reis','Sojasauce|80 ml;Honig|2 EL;Brokkoli|500 g'],['Zitronen-Hähnchen aus dem Ofen','Zitronen|2;Kartoffeln|800 g;Rosmarin|4 Zweige'],['Hähnchen-Reis-Topf','Reis|350 g;Möhren|3;Erbsen|200 g']],
    fisch:[['Lachs mit Ofenkartoffeln','Lachsfilet|600 g;Kartoffeln|1 kg;Brokkoli|500 g'],['Fischstäbchen selbst gemacht','Kabeljau|600 g;Paniermehl|150 g;Eier|2'],['Seelachs in Senfsauce','Seelachs|600 g;Senf|2 EL;Sahne|150 ml'],['Lachs-Spinat-Quiche','Lachs|350 g;Spinat|300 g;Mürbeteig|1'],['Fisch-Tacos mild','Weißfisch|600 g;Tortillas|8;Rotkohl|300 g'],['Thunfisch-Nudel-Salat','Thunfisch|2 Dosen;Pasta|400 g;Mais|1 Dose'],['Ofenfisch mit Tomaten','Fischfilet|600 g;Kirschtomaten|500 g;Oliven|80 g'],['Lachs-Reis-Bowl','Lachs|600 g;Reis|300 g;Gurke|1'],['Fischfrikadellen','Fischfilet|600 g;Ei|1;Paniermehl|80 g'],['Cremige Lachssuppe','Lachs|500 g;Kartoffeln|600 g;Lauch|1 Stange']],
    vegetarisch:[['Kichererbsen-Curry','Kichererbsen|2 Dosen;Kokosmilch|400 ml;Süßkartoffel|500 g'],['Gemüse-Curry mit Reis','Brokkoli|400 g;Möhren|3;Paprika|2'],['Linsenbolognese','rote Linsen|250 g;Möhren|2;Spaghetti|400 g'],['Gemüsefrikadellen','Zucchini|2;Möhren|3;Haferflocken|100 g'],['Falafel-Bowl','Falafel|500 g;Couscous|300 g;Gurke|1'],['Spinat-Feta-Pfannkuchen','Spinat|300 g;Feta|200 g;Eier|4'],['Ofengemüse mit Kräuterquark','Kartoffeln|600 g;Möhren|4;Zucchini|2'],['Veggie-Chili','Kidneybohnen|2 Dosen;Mais|1 Dose;Tomaten|800 g'],['Tomatenrisotto','Risottoreis|350 g;Tomaten|600 g;Parmesan|80 g'],['Brokkoli-Käse-Taler','Brokkoli|600 g;Käse|150 g;Eier|2']],
    suppe:[['Kartoffelsuppe klassisch','Kartoffeln|800 g;Lauch|1 Stange;Möhren|3'],['Hühner-Nudelsuppe','Hähnchen|500 g;Suppennudeln|200 g;Möhren|3'],['Tomatensuppe mit Reis','Tomaten|1 kg;Reis|120 g;Sahne|100 ml'],['Kürbiscremesuppe','Hokkaido|1;Kartoffeln|300 g;Kokosmilch|250 ml'],['Linseneintopf','Tellerlinsen|350 g;Kartoffeln|500 g;Möhren|3'],['Gemüseeintopf','Kartoffeln|500 g;Möhren|3;Bohnen|300 g'],['Brokkolicremesuppe','Brokkoli|700 g;Kartoffeln|300 g;Frischkäse|150 g'],['Minestrone','weiße Bohnen|1 Dose;kleine Nudeln|150 g;Tomaten|500 g'],['Erbsensuppe mild','Erbsen|500 g;Kartoffeln|400 g;Möhren|2'],['Gulaschsuppe familienfreundlich','Rindergulasch|600 g;Paprika|3;Kartoffeln|500 g']],
    kartoffeln:[['Kartoffelpuffer mit Apfelmus','Kartoffeln|1 kg;Apfelmus|400 g'],['Bratkartoffeln mit Spiegelei','Kartoffeln|1 kg;Eier|4;Speck optional|100 g'],['Kartoffelbrei mit Frikadellen','Kartoffeln|1 kg;Rinderhack|600 g;Milch|200 ml'],['Ofenkartoffeln mit Kräuterquark','Kartoffeln|1 kg;Quark|500 g;Kräuter|1 Bund'],['Bauernfrühstück','Kartoffeln|800 g;Eier|6;Paprika|1'],['Kartoffel-Gemüse-Puffer','Kartoffeln|700 g;Zucchini|1;Möhren|2'],['Kartoffelsalat mit Würstchen','Kartoffeln|1 kg;Würstchen|8;Gurke|1'],['Süßkartoffel-Pommes mit Dip','Süßkartoffeln|1 kg;Joghurt|250 g;Paprika|1 TL'],['Gefüllte Ofenkartoffeln','Kartoffeln groß|8;Mais|1 Dose;Käse|150 g'],['Rösti mit Lachs oder Gemüse','Kartoffeln|1 kg;Räucherlachs oder Gemüse|300 g;Quark|250 g']],
    fruehstueck:[['Fluffige Familien-Pancakes','Mehl|300 g;Milch|400 ml;Eier|3'],['Apfel-Zimt-Porridge','Haferflocken|250 g;Äpfel|3;Milch|700 ml'],['Ofen-Porridge mit Beeren','Haferflocken|300 g;Beeren|300 g;Bananen|2'],['Rührei mit Gemüse','Eier|8;Tomaten|3;Paprika|1'],['Frühstücks-Wraps','Tortillas|8;Eier|6;Käse|120 g'],['Joghurt-Granola-Becher','Joghurt|800 g;Granola|250 g;Beeren|300 g'],['Bananen-Hafer-Waffeln','Bananen|3;Haferflocken|250 g;Eier|3'],['Arme Ritter mit Beeren','Toast|8 Scheiben;Eier|3;Milch|250 ml'],['Käse-Schinken-Brötchen aus dem Ofen','Brötchen|8;Käse|200 g;Kochschinken|200 g'],['Obstiger Frühstücks-Smoothie','Bananen|3;Beeren|300 g;Joghurt|400 g']],
    backen:[['Saftiger Apfelkuchen','Äpfel|800 g;Zimt|2 TL;Mandeln|80 g'],['Marmorkuchen','Kakao|3 EL;Vanille|1 TL;Butter|200 g'],['Bananenbrot','Bananen reif|4;Walnüsse|80 g;Zimt|1 TL'],['Blaubeer-Muffins','Blaubeeren|300 g;Joghurt|150 g;Vanille|1 TL'],['Zitronenkuchen','Zitronen|2;Puderzucker|120 g;Butter|180 g'],['Schoko-Brownies','Schokolade|250 g;Kakao|40 g;Butter|200 g'],['Käsekuchen einfach','Quark|1 kg;Vanillepuddingpulver|1 Päckchen;Zitrone|1'],['Karottenkuchen','Möhren|400 g;Mandeln|200 g;Zimt|2 TL'],['Haferkekse','Haferflocken|250 g;Butter|120 g;Rosinen|80 g'],['Kirsch-Streuselkuchen','Kirschen|700 g;Butter|220 g;Zimt|1 TL']],
    orientalisch:[['Persisches Safranhähnchen mit Reis','Hähnchen|700 g;Safran|1 Prise;Berberitzen|80 g'],['Zereshk Polo familienfreundlich','Hähnchen|700 g;Berberitzen|100 g;Safran|1 Prise'],['Mildes Ghormeh Sabzi','Rindergulasch|600 g;Kräutermischung|500 g;Kidneybohnen|1 Dose'],['Persische Kräuter-Frittata','Eier|8;Kräuter gemischt|300 g;Walnüsse|60 g'],['Adas Polo mit Linsen','Reis|350 g;braune Linsen|250 g;Rosinen|80 g'],['Kofta in Tomatensauce','Rinderhack|600 g;Tomaten|800 g;Petersilie|1 Bund'],['Mildes Butter Chicken','Hähnchen|600 g;Joghurt|200 g;Tomaten|500 g'],['Türkische Linsensuppe','rote Linsen|300 g;Möhren|2;Zitrone|1'],['Couscous mit Ofengemüse','Couscous|350 g;Zucchini|2;Paprika|2'],['Shakshuka mild','Eier|8;Tomaten|800 g;Paprika|2']]
  };
  const parsePairs = value => value.split(';').map(part=>{const [name,quantity='nach Bedarf']=part.split('|');return {name,quantity}});
  let rank=0;
  window.FAMI_FAMILY_RECIPES = Object.entries(dishes).flatMap(([group,items])=>items.map(([title,extras],index)=>{
    const config=groups[group],nutrition={kcal:Math.round((360+((rank*37)%360))/10)*10,protein:14+((rank*7)%34),carbs:38+((rank*11)%58),fat:8+((rank*5)%23),label:'pro Portion',estimated:true};rank++;
    const extraPairs=parsePairs(extras),extraNames=new Set(extraPairs.map(item=>item.name.toLocaleLowerCase('de')));const basePairs=parsePairs(config.ingredients).filter(item=>!extraNames.has(item.name.toLocaleLowerCase('de'))&&!(group==='pasta'&&item.name==='Pasta'));
    const id=`family-${group}-${index+1}`;
    return {id,title,channel:'Fami Familienküche',url:'',image:`./images/family-recipes-v2/${id}.webp`,meta:`${config.time} · 4 Portionen · ★ 4,8`,views:200000-rank*1000,meal:config.meal,cuisine:config.cuisine,nutrition,featured:true,familyRecipe:true,recipe:{ingredients:[...extraPairs,...basePairs].map(item=>`${item.quantity} ${item.name}`),steps:config.steps.map(step=>step.replace('Hauptzutaten',title)),sourceType:'Fami Familienrezept · ohne YouTube',notice:'Nährwerte sind eine KI-Schätzung pro Portion. Mengen und Garzeit bitte an Produkte und Portionsgröße anpassen.'}};
  }));
})();
